version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile   # your existing Dockerfile
    container_name: orchestrator
    restart: unless-stopped
    environment:
      # Use the service DNS name "mongo" to reach the DB inside the compose network
      - MONGO_URL=mongodb://mongo:27017/orchestrator
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    # The orchestrator needs to talk to Docker to create/manage containers:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  mongo_data:
